ValveSoftware/steam-runtime

- build-runtime.py
Hard-coded beta repository was misspelled as steam_beta rather than scout_beta.
> Fix typo in build script

- .gitignore
- build-runtime.py
- setup_chroot.sh
- write-manifest
This PR adds manifest files to the Runtime and the corresponding SDK chroot listing the source and binary packages that went into the Runtime or SDK, in a tab-separated table that is suitable for machine-processing and also supported by many spreadsheets:
```
#Package[:Architecture]	#Version	#Source	#Installed-Size
dconf-gsettings-backend:amd64	0.12.0-0ubuntu1.1+srt4	d-conf	81
...
libgudev-1.0-0:amd64	1:175-0ubuntu9.2+srt4	udev (175-0ubuntu9.2+srt4)	187
```
The manifest is in a canonical sorting order, so that different runtimes can easily be compared with `diff -u`. Listing the source package (and its version number, if it differs from the binaries) lets us match binary packages to source packages for GPL compliance, and listing the installed size in Kbytes gives us an idea of what the …
> Write manifests listing everything in the Runtime/SDK

- tests/all-packages-published.py
This follows up from @TTimo's replacement of the hard tabs ("noexpandtab" in vim terms) with PEP-8's recommended 4-space indentation ("shiftwidth=4 softtabstop=4 expandtab" in vim, or "sw=4 sts=4 et" with conventional abbreviations) in commit d473ed43.
Now that this test is using 4-space indentation, it's also unnecessary to wrap long lines quite so aggressively.
> tests: Rewrap long lines, fix vim modeline

- .gitattributes
GitHub's language detection tool ([linguist](https://github.com/github/linguist)) is incorrectly detecting some of the license files as code.
This PR adds a .gitattributes file that excludes these files from being included in this visualization, [using the methods described in linguist's documentation.](https://github.com/github/linguist#documentation)
Oddly, use of `linguist` on my local machine produces no difference in results with or without this change, and I believe that the language breakdown preview on my fork has yet to be updated, so I cannot see 'live' results.
Here's the output when run locally.
```
$ linguist --version
Linguist v6.4.1
Detect language type for a file, or, given a repository, determine language breakdown.
Usage: linguist <path>
linguist <path> [--breakdown] …
```
> Add .gitattributes file to indicate license files are part of documentation

- sourcepkgs.list
- tests/all-packages-published.py
Otherwise fcitx-libs-dev won't necessarily be available to be included in the SDK. This discrepancy was detected by `make check`.
This branch also fixes the sense of the error message that detected it, which confused me at first :-)
> Publish src:fcitx in apt repository

- packages.txt
- tests/all-packages-published.py
libvulkan{1,-dev} 1.0.x were built by src:vulkan-loader, but the current version 1.1.73 is from a renamed source package, src:vulkan.
Detected by `make check`.
This also includes the same commit as #109 to fix the error message that detected this discrepancy.
> packages.txt: List libvulkan* as coming from src:vulkan

- .gitignore
- steam-runtime.docker
Following corrections were needed:
Reordering lines ARG and FROM prevents docker from failing with error:
Step 1/18 : ARG arch=amd64
Please provide a source image with `from` prior to commit
Additional package installation to prevent `resolvconf` from failing with message about no symlink.
Additional package installation of `install-info` to prevent post-installation step of `time` from stopping whole image creation.
Also, the `.gitignore` file was updated to prevent accidental commit of generated image files.
These changes enable the creation of images on Fedora, CentOS, RHEL and presumably any other distro using Docker 1.1x. Without this, I cannot follow steps to build Proton on my machine.
> Fix steam-runtime dockerfile for Docker 1.13

- Makefile
- build-runtime.py
- tests/pycodestyle.sh
- tests/pyflakes.sh
pyflakes and (to a lesser extent) pycodestyle can often act as an early-warning system for bugs.
This branch adds pyflakes and pycodestyle checks in `make check`, and fixes a non-intrusive subset of pycodestyle warnings for `build-runtime.py`.
> build-runtime: Add pyflakes and pycodestyle checks

- .gitignore
- debos-chroot.yaml
This matches the behaviour of the runtime tarballs.. Use "debos -t official:yes ..." to get an official tarball.
> Mark schroot tarballs as unofficial by default

- build-runtime.py
For example, "./build-runtime.py ... --suite=scout-misc-backports"
was intended to produce
unofficial-steam-runtime-scout-misc-backports-release_20181106.tar.xz.
Without this fix, it would just crash.
> Fix runtime prefix naming for non-beta, non-scout apt suites

- debos-chroot.yaml
- scripts/bootstrap-runtime.sh
- setup_chroot.sh
This can be used to make a runtime schroot from a modified copy of the Steam Runtime.
> schroot: Add support for non-default apt suites

- build-runtime.py
Not all third-party apt repositories support detached debug symbols with the same layout as the official Steam Runtime repository.
> build-runtime: Survive HTTP errors when downloading debug packages

- build-runtime.py
If we know the Runtime should have a particular package, it probably
doesn't make sense to continue to build a Runtime without it.
> build-runtime.py: Add --strict option to fail on missing packages

- build-runtime.py
This matches the format in which it gets delivered by the Steam client. Recent Runtime versions are a little smaller than they have historically been, so we need to make sure to create .part2 (even if it's empty) to avoid this failure mode:
* Steam user has an older Runtime (parts 0 to 2 are non-empty)
* client updates to a newer Runtime (parts 0 to 1)
* `cat steam-runtime.tar.xz.part* > steam-runtime.tar.xz`
* now steam-runtime.tar.xz contains parts 0 to 1 of the new runtime
and part 2 of the old runtime, and is a corrupt archive
---
This branch currently depends on and includes #128, but it could be rebased to avoid that if #128 is problematic for some reason.
> build-runtime.py: Optionally split runtime into parts

- build-runtime.py
If files in ./templates (or the argument to --templates if different)
are changed or added, while reusing an existing ./runtime (or the
argument to --runtime if different), then we would unexpectedly fail to
update those files. For example, after fixing a bug in run.sh, we
wouldn't pick up the fixed version in the runtime until we either use
a different target directory or delete and recreate ./runtime.
Similarly, if files in ./templates are removed, their counterparts in
./runtime would stay until we either switch to a different target
directory or delete ./runtime.
If we require the caller to give us a nonexistent target directory, it
becomes completely clear what is going on, and makes the caller
responsible for doing the right thing (either using a different target
directory for each …
> build-runtime.py: Require that runtime doesn't exist and templates does

- packages.txt
- sourcepkgs.list
packages: Include libmpg123 shared libraries, not mpg123 executable
It's important that we distinguish between source packages (the first column of this file) and binary packages (every other column).
libsdl2-mixer dlopens libmpg123.so.0 to play MP3 audio, so we want that in the Runtime, otherwise games that use SDL for MP3 audio won't work unless the host system happens to have libmpg123-0 (or equivalent) installed on it.
We don't want /usr/bin/mpg123, the command-line MP3 player, which is useless without libmpg123.
Similarly, we presumably want development runtimes to have libmpg123-dev, the development headers for this MP3 playback library, rather than the nonexistent mpg123-dev.
I've assumed that we don't need libout123, which appears to be an audio output abstraction layer analogous …
> Fix packages.txt, sourcepkgs.list for inclusion of new SDL's dependencies

- README.md
- build-runtime.py
Prior to commit 31764950, the --runtime directory (default: ./runtime)
was both an input and an output, and was always populated.
Now that it's only an output, with --templates=./templates taking the
input role, rename the option to --output to make this more clear.
While I'm making incompatible changes anyway, instead of giving it a
new default, I've given it no default. Instead, we require at least one
of --output and --archive. If the only thing we are interested in
generating is a tar archive (as is the case for the official Steam
Runtime binary releases provided alongside Steam), then we can build
the runtime in a temporary directory, compress it into the archive, and
discard the temporary directory, removing the need for a wrapper script
to manage the temporary directory.
> build-runtime: Rename --runtime to --output, and take away the default

- .gitattributes
For mingw/cygwin execution on Windows.
(Patch from @TTimo)
> Keep .sh files with LF line endings

- docker_fetch_base_cloudimg.sh
This fixes "gpg: cannot open '/dev/tty': No such device or address"
error when running in current Debian 9.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913614#27
> Run gpg2 in --batch mode

- build-runtime.py
When sorting archive members by name, we normalized `foo` to `./foo`
as intended, but also normalized `.` to `./.` not as intended. This
resulted in a predictable but odd archive order where the immediate
children of the top-level directory (including subdirectories like
amd64/ and scripts/) were all sorted before the contents of any
subdirectory (including for example amd64/).
Signed-off-by: Simon McVittie <smcv@collabora.com>
> build-runtime: Improve normalization for paths in archive

- docker_fetch_base_cloudimg.sh
In Debian 10 'buster', gpg and gpgv are version 2, and the gpg2 and
gpgv2 names are provided by compatibility packages that are not
normally installed.
Check for the names with the "2" suffix first, in case we're running
on an older OS.
> docker_fetch_base_cloudimg.sh: Allow either gpg(v)2 or gpg(v)

- .gitattributes
This is a trivial patch to fix the project's egregious classification as a Roff repository:
These three files are to blame, as GitHub thinks they're manpages because their filenames end in `.2`, `.1` and `.3`, which are common file extensions used by man-pages:
* [`templates/common-licenses/GFDL-1.2`](https://github.com/ValveSoftware/steam-runtime/blob/e019f6dcbf2dc57e6d249b72d8f5327b3653a9f7/templates/common-licenses/GFDL-1.2)
* [`templates/common-licenses/GFDL-1.3`](https://github.com/ValveSoftware/steam-runtime/blob/e019f6dcbf2dc57e6d249b72d8f5327b3653a9f7/templates/common-licenses/GFDL-1.3)
* [`templates/common-licenses/LGPL-2.1`](https://github.com/ValveSoftware/steam-runtime/blob/e019f6dcbf2dc57e6d249b72d8f5327b3653a9f7/templates/common-licenses/LGPL-2.1)
> Fix project's misclassification on GitHub

- setup_docker.sh
- steam-runtime.docker
This branch refactors `setup_docker.sh` to use `getopt` for consistent option parsing, then adds `--proxy` and `--no-proxy` options, defaulting to `${http_proxy}` and `${no_proxy}` respectively. It also configures apt in the Docker container to use `DIRECT` mode for hosts listed in `no_proxy` (subdomains like `no_proxy=.example.com` are not currently supported).
> docker: Add support for no_proxy

- steam-runtime.docker
Previously we were recording the Ubuntu packages before converting the
container to SteamRT with bootstrap-runtime.sh, which was misleading.
> docker: Record contents of Docker image after SteamRT conversion

- .gitignore
- build-runtime.py
- tests/build-runtime.py
- tests/pycodestyle.sh
- tests/read-manifests.py
- tests/third-party/pycotap.py
- webhelper/packages.txt
To test, for example:
```
python3 ./build-runtime.py \
--arch amd64 \
--archive runtime/ \
--repo http://.../steamrt-heavy \
--set-version ... \
--suite heavy \
--packages-from webhelper/packages.txt \
--extra-apt-source 'both http://deb.debian.org/debian jessie main' \
--extra-apt-source 'both http://deb.debian.org/debian jessie-updates main' \
--extra-apt-source 'both http://security.debian.org/debian-security jessie/updates main' \
--verbose \
--strict \
${NULL}
```
> Add support for a jessie-based mini-runtime

- debian/changelog
- debian/control
- debian/rules
- debian/tests/control
- debian/tests/extra-bootstrap.sh
- debian/tests/setup-chroot.py
- debian/tests/setup-docker.py
- tests/mypy.sh
- tests/pycodestyle.sh
- tests/pyflakes.sh
- tests/third-party/pycotap.py
Because these tests manipulate Docker and schroot, and use sudo, they should be run on a virtual machine (or a real machine that you don't mind possibly breaking); in particular they can't be run inside a typical Docker container. Debian's autopkgtest tool already knows how to run tests in qemu virtual machines, and we can make use of it by adding the basic structure of a Debian source package.
Example of use:
autopkgtest-buildvm-ubuntu-cloud \
--arch amd64 \
--release bionic \
${http_proxy+--proxy "${http_proxy}"} \
--verbose
autopkgtest \
--no-built-binaries \
${http_proxy+--env http_proxy="${http_proxy}"} \
${https_proxy+--env https_proxy="${https_proxy}"} \
${no_proxy+--env no_proxy="${no_proxy}"} \
. -- qemu autopkgtest-bionic-amd64.img
This branch also adds some supporting …
> Add automated tests for setup_*.sh

- debian/changelog
- debian/control
- debian/rules
- debian/tests/control
- debian/tests/extra-bootstrap.sh
- debian/tests/setup-chroot.py
- debian/tests/setup-docker.py
- scripts/bootstrap-runtime.sh
- setup_chroot.sh
- setup_docker.sh
- templates/run.sh
- tests/mypy.sh
- tests/pycodestyle.sh
- tests/pyflakes.sh
- tests/shellcheck.sh
- tests/third-party/pycotap.py
This branch continues from #150, so please review that one first (or I can rebase this one if maintainers would prefer to merge it first).
It adds [shellcheck](https://www.shellcheck.net/) coverage for various shell scripts. `shellcheck` is a lint tool for Bourne shell and bash scripts which detects various common mistakes, particularly around code that would go wrong if filenames and other strings contain spaces.
> Check shell scripts with shellcheck

- templates/setup.sh
This branch adds `templates/setup.sh`, which becomes `./setup.sh` in a Steam Runtime tarball. It sets up the "pinned" libraries using code adapted from the Steam client's `steam.sh` (thanks to @TTimo for agreeing to relicense this). This makes the Steam Runtime more self-contained and less dependent on the Steam client. Previously, `templates/run.sh` knew how to use libraries that had been pinned by `steam.sh`, but the Steam Runtime relied on the Steam client to set up the pinning.
The purpose of the "pinned" libraries is to get the right precedence when using a mixture of host-system and Steam Runtime libraries. If the version in the Runtime is newer, we have to use it, because a game might depend on updated functionality (for example we have some very new audio decoder libraries in …
> Add setup.sh to script templates

- setup_chroot.sh
Making the debootstrap process safe to run on arbitrary user systems is relatively involved, and we can get more predictable results by distributing a complete tarball that corresponds 1:1 to a specific version of a runtime. If we build Docker images, the sysroot tarball is essentially the same as the contents of the Docker image.
In particular, this branch makes `./setup_chroot.sh --suite=heavy` (or any of the other TF2 classes) fail with a warning, unless you also add the new `--tarball` option. This is because `scripts/bootstrap-runtime.sh` assumes that it's operating on `scout`, an Ubuntu 12.04 derivative, and future Steam Runtimes codenamed after different TF2 classes are unlikely to be 12.04-based.
> setup_chroot.sh: Add support for importing prebuilt sysroot tarballs

- build-runtime.py
Previously, --compression had no practical effect.
> build-runtime.py: Reinstate support for non-xz compression

- templates/setup.sh
The shellcheck in Debian 10 'buster' doesn't warn about this, but the
version in Debian 9 'stretch' does. The code does the right thing
either way (it expands to the equivalent of either `[ ! -z ]`, which
fails as desired, or `[ ! -z isset ]`, which succeeds as desired), but
it's more obviously correct if we quote it, turning the first case into
`[ ! -z "" ]` (which also fails, as desired).
> templates/setup.sh: Improve robustness of quoting

- webhelper/packages.txt
While working on a metapackage-based approach to package selection for the runtime tarball, I wrote some code to check that for every library in our runtime, we also ship each of its dependencies (with some exceptions for things that we expect to get from the host system, like libc6 and libgl1, and for things that are needed at install-time but not during use, like debconf).
This flagged a few dependencies that we are not currently installing:
* libnss3 depends on libsqlite3-0, which we can't count on being available in the host system. We should add it.
* libx1-6 depends on libx11-data, which is in the main runtime but not in the one for the webhelper. I don't know how necessary this really is, but the conservative thing to do would be to add it here.
* libgcc1 (built by src:gcc-4.9) …
> Add some missing packages to webhelper/packages.txt

- build-runtime.py
- tests/mypy.sh
- webhelper/packages.txt
Instead of duplicating the lists of desired packages in the steamrt
source package and in packages.txt, it would be useful to be able to
have a "single source of truth". When testing new packages we need an
extra apt source (--extra-apt-source) to fetch those packages from
anyway, so it seems natural to add an updated steamrt source package to
that repository and use it as our single source of truth.
This will mean we can add or update new batches of packages, like the
GNUTLS 3 transition in #101, without temporarily breaking the public
version of steam-runtime.git for third-party users by making it rely
on packages that have not yet gone out to the public.
With the modified steamrt package that I'm preparing to accompany this
change, the metapackage equivalent of the default behaviour …
> Optionally use metapackages to populate the runtime

- tests/read-manifests.py
When we use metapackages to build the runtime, they'll end up installed
even though they aren't listed in packages.txt.
> tests/read-manifests: Allow binary packages from src:steamrt

- README.md
- build-runtime.py
- tests/read-manifests.py
Instead of generating a basename from the name and version, sometimes
it's useful to be able to set a predictable basename directly.
---
Also includes this related change:
build-runtime.py: Create DIR/*.version.txt if --archive=DIR/ was used
This will let us see what the latest version is, even if the filenames
don't contain it.
----
Also includes #160.
> build-runtime.py: Allow archive basename in a directory to be given explicitly

- build-runtime.py
Previously, we only did this if the argument to --archive ended with '/', but it's equally useful if we use `--archive=/some/dir/tarball.*` or `--archive=/some/dir`. There's a minor special case for `--archive=foo.tar.xz`, in which case `os.path.dirname` returns `""`.
> build-runtime: Automatically create directory for --archive

- build-runtime.py
* Cope with a missing date in apt repositories' metadata.
* When download fails, log the URL before the error.
* In the EOL Debian jessie repository, several versions of gcc-4.9 appear in Sources with Extra-Source-Only: yes, but do not appear in the package pool. Ignore those versions when downloading source code, fixing the build of the 'heavy' runtime.
> Fix source code downloads

- build-runtime.py
A future Steam Runtime will include libcapsule-tools-relocatable (at
least in the debug runtime) to manipulate shared libraries and shared
library dependencies, and that package depends on libelf1. libelf1
itself doesn't seem important enough to elevate it to part of the
Steam Runtime's guaranteed ABI.
> build-runtime: Add libelf1 to runtime if something depends on it

- templates/setup.sh
UNTESTED: I don't have Risk of Rain, so I don't know whether this fixes it. (It at least doesn't seem to break the Steam client...)
---
libcurl in the Steam Runtime has a Debian-specific oddity (inherited by
Ubuntu and SteamRT) in which libcurl.so.3 is a symlink to libcurl.so.4,
as a result of some unfortunate ABI weirdness back in 2007 (upstream
bumped the SONAME in a situation where it might not in fact have been
necessary).
It also has Debian-specific symbol versioning, as a result of the
versioned symbols introduced as a Debian-specific change in 2005-2006
being preserved across the rename from libcurl.so.3 to libcurl.so.4
in 2007, and not matching the versioned symbols that upstream
subsequently added (in 2011). Versions of Debian and Ubuntu between
2011 and 2018 (including Ubuntu …
> Force libcurl.so.[34] to be taken from the Steam Runtime

- build-runtime.py
In Ubuntu, automatic -dbgsym packages are generated with the .ddeb
extension.
The apt repositories currently available on
<http://repo.steampowered.com/> were built with a modified reprepro
originating from <https://bugs.debian.org/730572>, which diverts
ddebs to a pseudo-component like "main/debug", similar to the existing
handling of udebs. Most of the changes from #730572 were never accepted
into upstream reprepro.
To avoid maintaining a patched reprepro indefinitely, it might be a good
idea to change debhelper so it puts the -dbgsym packages in ordinary
.deb files. This change makes build-runtime look in both package lists
so that it can cope either way.
Signed-off-by: Simon McVittie <smcv@collabora.com>
> build-runtime: Also look for debug symbols in normal Packages file

- build-runtime.py
The Steam Runtime has historically been built in two flavours,
"release" and "sym-src-debug". The sym-src-debug version is built with
the --symbols and --debug options.
The --symbols option adds detached debug symbols, which is entirely
reasonable.
The --debug option does two orthogonal things:
- It adds more packages. Historically, this was selected by filtering
packages.txt differently; now it uses different metapackages to
achieve the same result.
- It switches from the 'main' component in the apt repository to a
separate 'debug' component. This contains an independent build of
each package, built at a different time with a different version
number. If we are unlucky, the debug builds will also have been
built with different dependencies, or in pathological cases maybe
even from …
> build-runtime: Build the debug runtime from the 'main' component

- build-runtime.py
If the metapackage fails to depend on a library, also warn about any libraries that it depends on, and any libraries that *they* depend on, and so on. This makes it quicker to check missing dependencies.
> build-runtime.py: Warn about missing dependencies recursively

- scripts/bootstrap-runtime.sh
They're in the apt repository and will likely be pulled in by future
versions of the steamrt-dev metapackage.
> bootstrap-runtime: Offer gcc-5 and clang-3.8 if available

- build-runtime.py
As documented in `info gdb "Separate Debug Files"`, gdb looks for
build-ID-based debug symbols for a library with build ID 0123456789abcdef
under the name `.build-id/01/23456789abcdef.debug`. Previously we
created `usr/lib/debug/.build-id/01/23456789abcdef`, without the
`.debug` extension.
> build-runtime: Create debug symbol symlinks with the name gdb looks for

- build-runtime.py
- templates/run.sh
- templates/setup.sh
- tests/pycodestyle.sh
This PR pulls in the version of the steam-runtime tools that was used to build beta 0.20190913.0. It should also be fine to run against the state of older releases in the apt repository.
(@TTimo, you might want to push this as a fast-forward, instead of clicking Merge in the web UI, which will result in a merge commit.)
Summary of changes:
* Cope with newer `steamrt` metapackages having more diagnostic tools, which pull in more dependencies.
* Discard some NVIDIA Cg example source code, partially addressing #77 and reducing the size of the runtime.
* Combine most of the architecture-specific directories into a single merged directory hierarchy. `amd64/usr/bin` and `i386/usr/bin` remain architecture-dependent (we will use `amd64/usr/bin`, unless running on an (unsupported) 32-bit system, …
> Catch up with Steam Runtime 0.20190913.0

- README.md
As noted on #180, now that we have predictable, prebuilt sysroot tarballs that correspond exactly to a particular Steam Runtime beta or release, we should probably be recommending those rather than making everyone run debootstrap for themselves.
This also seems a good opportunity to recommend Docker over schroot. Our SDK image is not currently available on Dockerhub or in any other public registry, but each Steam Runtime release does come with a Dockerfile that can be used to convert the sysroot tarball into a Docker image.
cc @noncopyable
---
* README: Recommend using a prebuilt Steam Runtime snapshot
* README: Recommend using a prebuilt sysroot for development
* README: Update list of compiler versions
> Update README to recommend prebuilt tarballs

- build-runtime.py
- setup_chroot.sh
- templates/run.sh
- templates/setup.sh
- tests/pycodestyle.sh
(This is based on #181: please review that first.)
Being able to change the name makes it easier to experiment with the `--tarball` option, by using something like
./setup_chroot.sh --name steamrt_scout_sysroot_amd64 --tarball ~/Downloads/com.valvesoftware.SteamRuntime.Sdk-amd64\,i386-scout-sysroot.tar.gz --amd64
to get parallel `steamrt_scout_amd64` and `steamrt_scout_sysroot_amd64` chroots.
> setup_chroot.sh: Allow changing the chroot name

- build-runtime.py
- templates/setup.sh
When adding extra apt sources with `--extra-apt-source`, if the amd64 and i386 `Packages` metadata files for the extra apt source both contain both amd64 and i386 packages, `build-runtime.py` gets confused and installs the amd64 package twice (in fact it will install whichever package appears first, but in the situation where I encountered this, the amd64 package came first in both Packages files). This branch fixes that failure mode.
----
* build-runtime: Centralize logging of skipped downloads
* Make verbose mode more verbose
When something goes wrong with downloading and unpacking archives,
this makes it clearer what is going on.
* Ignore i386 packages in the amd64 Packages file and vice versa
The apt repositories generated for personal branches in the Open Build
Service have separate …
> Ignore packages of the wrong architecture in Packages files

- setup_chroot.sh
If `--name` wasn't explicitly used, the warning would say
About to remove /var/chroots/ and re-install...
which sounds more drastic than what will actually happen.
> Fix misleading warning message

- README.md
- scripts/dbgsym-use-build-id
The dbgsym-use-build-id script was taken from
<https://gitlab.collabora.com/smcv/flatdeb>. It is only necessary as long
as the production version of the Steam Runtime was built with a version
of flatdeb that did not have that script.
> Document how to use detached debug symbols with the Steam Runtime

- setup_chroot.sh
https://github.com/koalaman/shellcheck/wiki/SC2027
In this case, removing the double quotes I think makes more sense as you probably want to expand the argument.
> Removed unnecessary double quote SC2027

- doc/reporting-steamlinuxruntime-bugs.md
I personally find this method to be more convenient, however it does fail to capture some information from Steam startup as it only captures logs from the game (and Pressure Vessel).
> Add different method for capturing debug log

- doc/possible-designs.md
- doc/steamlinuxruntime-known-issues.md
* doc: Update version of o.fd.Platform in diagrams
* doc: Update "possible designs" document for current status
Some of these designs have now been implemented.
* doc: Document recent Flatpak development
With Flatpak 1.11.1, it is possible to run Proton games in a subsandbox.
* doc: Update for Mesa 20.3.5
Mesa 20.3.5 was released and does contain the same change as 21.0.0.
* doc: Stop documenting Vulkan layers as a known issue
We now share most, if not all, Vulkan layers with the container.
> Update documentation of known issues, etc.

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- doc/reporting-steamlinuxruntime-bugs.md
- doc/steamlinuxruntime-known-issues.md
* known-issues: Mention flatpak#4286
* reporting-bugs: Ask for SteamLinuxRuntime version numbers
* known-issues: Suggest the Flatpak app as a workaround for non-FHS hosts
* known-issues: Mention unprivileged_userns_clone=0 conflict with Flatpak
A setuid version of bwrap is enough to make pressure-vessel work, but
is not enough for it to work when used in conjunction with Flatpak.
* known-issues: Mention scout_layered_slim
This avoids some issues in games that assume a newer-than-scout
environment, but it has a different toolmanifest.vdf, which Steam does
not currently reload automatically after a depot is changed.
> Update known issues, workarounds and bug reporting instructions

- doc/possible-designs.md
* possible-designs: Update status of Arch "native runtime"
If 2019 Arch and 2012 Ubuntu were too different, then 2021 Arch and
2012 Ubuntu are certainly too different.
* possible-designs: Update status of Flatpak support
* possible-designs: Layered runtime has been implemented, as a beta
We described this here as unimplemented, but in fact we have now
implemented it.
> Update design document to reflect implementation status

- templates/setup.sh
We don't expect the end users to know what the "pins" are needed for or
what they even are.
Create instead a window with a more understandable message and title.
> setup: Create more user-friendly zenity messages

- templates/setup.sh
- setup: Use parameter expansion instead of basename
By switching to the bash parameter expansion we have a speedup of nearly
1 second on recent desktop systems with NVME, and probably more on
slower systems.
They are not exactly the same, but here we are using a somewhat
controlled input, `find` of libraries in the absolute path of the steam
runtime, so it should not give us unexpected results.
- setup: Start to use the executable from steam-runtime if available
The constant context switch to call the external command `file -L`
thousands of times makes the whole setup last several seconds.
steam-runtime-tools provides a new executable that gathers the libraries
list from ldconfig, or from a specified directory, and prints in output
their word size, all in one go.
By using this new method …
> Considerably speedup the setup phase

- templates/run.sh
Currently the only expected flag in `STEAM_COMPAT_FLAGS` is
`search-cwd`, that is used to append the game current working directory,
stored in `STEAM_COMPAT_INSTALL_PATH`, to the `LD_LIBRARY_PATH`.
Previously we handled this flag in pressure-vessel, but this may give
`STEAM_COMPAT_INSTALL_PATH` an higher priority than expected.
For example, when we are using the new layered scout runtime,
`STEAM_COMPAT_INSTALL_PATH` will be searched before the container
runtime's linker paths and the Steam Runtime's library paths.
> run.sh: Handle STEAM_COMPAT_FLAGS environment variable

- templates/setup.sh
realpath isn't Essential in very old Ubuntu releases (at least 14.04)
so there's no guarantee that it's available, whereas readlink has been
part of coreutils since time immemorial.
> templates: Use readlink -f instead of realpath

- doc/possible-designs.md
- doc/reporting-steamlinuxruntime-bugs.md
- doc/steamlinuxruntime-known-issues.md
* Update status of sniper to reflect it starting to be used in production
* Update status of shared non-home directories to reflect yesterday's beta update
* Update release status of Flatpak 1.12
* Add another cross-link between sections
* Update status of kernel.unprivileged_userns_clone in modern distros
> Documentation updates

- README.md
- doc/steamlinuxruntime-known-issues.md
The default branch has been renamed to `main`, and our earlier attempts to provide branch-independent links were thwarted by [a Gitlab regression](https://gitlab.com/gitlab-org/gitlab/-/issues/371973).
> doc: Update default branch reference for steam-runtime-tools

- doc/building-custom-runtime.md
Historically STEAM_RUNTIME has had a dual role as an unsupported developer/debugging input to steam.sh (to use a non-default runtime, or disable the scout runtime completely) and as an output from steam.sh (to indicate to games, libraries and utilities that they are running in the scout runtime).
This is quite confusing, so we're in the process of introducing a new variable STEAM_RUNTIME_SCOUT which can be set to the absolute path to a non-default runtime, and is unambiguously only an input: if it's set, that doesn't imply anything about whether you are inside the LDLP runtime or not. This was already used by the
"Steam Linux Runtime 1.0 (scout)" compatibility tool, which couldn't use STEAM_RUNTIME because that variable gets unset by the container runtime framework.
To be compatible with …
> doc: Set both STEAM_RUNTIME_SCOUT and STEAM_RUNTIME for custom runtimes

- README.md
- build-runtime.py
* README: Ubuntu 14.04 no longer works, mention 16.04 instead
Ubuntu 16.04 is the minimum version since steam-launcher 1.0.0.76.
* README: Link to Steam Runtime SDK docs instead of repeating ourselves
Adding and updating detailed documentation in this repository is
inconvenient, because for historical reasons its git history contains
large binaries, which cannot be removed without invalidating branches
and forks of the repository.
Each branch of the Steam Runtime has its own SDK hosted elsewhere,
so link to those as the primary thing to use.
* README: Mention Distrobox as an alternative to Toolbx
Either one should usually work equally well.
Resolves: https://github.com/ValveSoftware/steam-runtime/issues/739
* Update introduction to reflect reality as of early 2025
- Native sniper games …
> Documentation updates, drop vestigial support for heavy
